import xoPagination from './Pagination.vue'
import xoDatePicker from './DatePicker.vue'
import xoNavPath from './NavPath.vue'
import xoButton from './Button.vue'
import xoAuth from './Auth.vue'
import xoAffiliatedStore from './AffiliatedStore.vue'
import xoPubTree from './PubTree.vue'
import xoDishes from './Dishes'
import xoForm from './Form'
import xoThemePicker from './ThemePicker'
export default {xoPagination,xoDatePicker,xoNavPath,xoButton,xoAuth,xoAffiliatedStore,xoPubTree,xoDishes,xoForm,xoThemePicker}
